
[environment]
active = 0
#   0: development
#   1: docker
port = 8082

[log_file_path]
trace = "trace.log"
info = "info.log"
warning = "warning.log"
error = "error.log"
xml = "logFile.xml"

[db]
port = "27017"
db_name = "eventstore"
doc_name = "events"
pool_limit = 100
timeout = 10

[uri]
api = "/api"
system_event = "/systemevent"
user_command = "/usercommand"
quote_server = "/quoteserver"
error_event = "/errorevent"
account_transaction = "/accounttransaction"
log_all = "/log"
log = "/log/:userName"
clear_db = "/clear-db"
