[messages]


    [messages.error]
    db_conn_err = "Failed to connect MongoDB database."
    serialize_object_error = "Failed to serialize object."
    unserialize_object_error = "Failed to unserialize object."
    to_array_error = "Failed to convert an object to an array."
    to_map_error = "Failed to convert an object to a map."
    invalid_env_type = "There is no such running environment."
    db_insert_error = "Failed to insert an event into db."
    db_update_by_id_error = "Failed to update an event in the db."
    db_delete_error = "Failed to delete an event in the db."
    db_find_all_error = "Failed to find all events in the db."
    db_find_by_user_id_error = "Failed to find any events by the given user."
    no_user_id_available_error = "There is no user id available for an event."
    create_log_file_error = "Failed to create log file."

    [messages.warning]
    no_events_found_warning = "There is no available event in db"
    no_events_found_by_user_warning = "There is no event available with the given user id"
  